/*
 * PsaiXmlConstants.cpp
 *
 *  Created on: 06-Jan-2009
 *      Author: tim
 */

#include "PsaiXmlConstants.h"

namespace PsaiXmlConstants
{
const String TYPE_VECTOR_3D("psai:vector3d");
const String TYPE_CONTAINER_CONTENTS("psai:containercontents");
const String TYPE_ITEM_DESCRIPTION("psai:itemdescription");
const String TYPE_NETWORK_DETAIL_SKILL("psai:networkdetailskill");
const String TYPE_NET_WEATHER_INFO("psai:netweatherinfo");
const String TYPE_PS_MONEY("psai:psmoney");

// enumerated types

// Message Class Types
const String MSGTYPE_PING("MSGTYPE_PING");
const String MSGTYPE_AUTHENTICATE("MSGTYPE_AUTHENTICATE");
const String MSGTYPE_PREAUTHENTICATE("MSGTYPE_PREAUTHENTICATE");
const String MSGTYPE_PREAUTHAPPROVED("MSGTYPE_PREAUTHAPPROVED");
const String MSGTYPE_AUTHAPPROVED("MSGTYPE_AUTHAPPROVED");
const String MSGTYPE_AUTHREJECTED("MSGTYPE_AUTHREJECTED");
const String MSGTYPE_DISCONNECT("MSGTYPE_DISCONNECT");
const String MSGTYPE_CHAT("MSGTYPE_CHAT");
const String MSGTYPE_GUILDCMD("MSGTYPE_GUILDCMD");
const String MSGTYPE_USERCMD("MSGTYPE_USERCMD");
const String MSGTYPE_SYSTEM("MSGTYPE_SYSTEM");
const String MSGTYPE_CHARREJECT("MSGTYPE_CHARREJECT");
const String MSGTYPE_DEAD_RECKONING("MSGTYPE_DEAD_RECKONING");
const String MSGTYPE_CELPERSIST("MSGTYPE_CELPERSIST");
const String MSGTYPE_CONFIRMQUESTION("MSGTYPE_CONFIRMQUESTION");
const String MSGTYPE_USERACTION("MSGTYPE_USERACTION");
const String MSGTYPE_ADMINCMD("MSGTYPE_ADMINCMD");
const String MSGTYPE_GUIINTERACT("MSGTYPE_GUIINTERACT");
const String MSGTYPE_GUIINVENTORY("MSGTYPE_GUIINVENTORY");
const String MSGTYPE_VIEW_ITEM("MSGTYPE_VIEW_ITEM");
const String MSGTYPE_VIEW_CONTAINER("MSGTYPE_VIEW_CONTAINER");
const String MSGTYPE_VIEW_SKETCH("MSGTYPE_VIEW_SKETCH");
const String MSGTYPE_VIEW_ACTION_LOCATION("MSGTYPE_VIEW_ACTION_LOCATION");
const String MSGTYPE_READ_BOOK("MSGTYPE_READ_BOOK");
const String MSGTYPE_WRITE_BOOK("MSGTYPE_WRITE_BOOK");
const String MSGTYPE_UPDATE_ITEM("MSGTYPE_UPDATE_ITEM");
const String MSGTYPE_MODE("MSGTYPE_MODE");
const String MSGTYPE_WEATHER("MSGTYPE_WEATHER");
const String MSGTYPE_NEWSECTOR("MSGTYPE_NEWSECTOR");
const String MSGTYPE_GUIGUILD("MSGTYPE_GUIGUILD");
const String MSGTYPE_EQUIPMENT("MSGTYPE_EQUIPMENT");
const String MSGTYPE_GUIEXCHANGE("MSGTYPE_GUIEXCHANGE");
const String MSGTYPE_EXCHANGE_REQUEST("MSGTYPE_EXCHANGE_REQUEST");
const String MSGTYPE_EXCHANGE_ADD_ITEM("MSGTYPE_EXCHANGE_ADD_ITEM");
const String MSGTYPE_EXCHANGE_REMOVE_ITEM("MSGTYPE_EXCHANGE_REMOVE_ITEM");
const String MSGTYPE_EXCHANGE_ACCEPT("MSGTYPE_EXCHANGE_ACCEPT");
const String MSGTYPE_EXCHANGE_STATUS("MSGTYPE_EXCHANGE_STATUS");
const String MSGTYPE_EXCHANGE_END("MSGTYPE_EXCHANGE_END");
const String MSGTYPE_EXCHANGE_MONEY("MSGTYPE_EXCHANGE_MONEY");
const String MSGTYPE_GUIMERCHANT("MSGTYPE_GUIMERCHANT");
const String MSGTYPE_GROUPCMD("MSGTYPE_GROUPCMD");
const String MSGTYPE_GUIGROUP("MSGTYPE_GUIGROUP");
const String MSGTYPE_STATDRUPDATE("MSGTYPE_STATDRUPDATE");
const String MSGTYPE_SPELL_BOOK("MSGTYPE_SPELL_BOOK");
const String MSGTYPE_GLYPH_REQUEST("MSGTYPE_GLYPH_REQUEST");
const String MSGTYPE_GLYPH_ASSEMBLE("MSGTYPE_GLYPH_ASSEMBLE");
const String MSGTYPE_PURIFY_GLYPH("MSGTYPE_PURIFY_GLYPH");
const String MSGTYPE_SPELL_CAST("MSGTYPE_SPELL_CAST");
const String MSGTYPE_SPELL_CANCEL("MSGTYPE_SPELL_CANCEL");
const String MSGTYPE_EFFECT("MSGTYPE_EFFECT");
const String MSGTYPE_EFFECT_STOP("MSGTYPE_EFFECT_STOP");
const String MSGTYPE_NPCAUTHENT("MSGTYPE_NPCAUTHENT");
const String MSGTYPE_NPCLIST("MSGTYPE_NPCLIST");
const String MSGTYPE_GUITARGETUPDATE("MSGTYPE_GUITARGETUPDATE");
const String MSGTYPE_MAPLIST("MSGTYPE_MAPLIST");
const String MSGTYPE_NPCOMMANDLIST("MSGTYPE_NPCOMMANDLIST");
const String MSGTYPE_ALLENTITYPOS("MSGTYPE_ALLENTITYPOS");
const String MSGTYPE_NEW_NPC("MSGTYPE_NEW_NPC");
const String MSGTYPE_PETITION("MSGTYPE_PETITION");
const String MSGTYPE_MSGSTRINGS("MSGTYPE_MSGSTRINGS");
const String MSGTYPE_CHARACTERDATA("MSGTYPE_CHARACTERDATA");
const String MSGTYPE_AUTHCHARACTER("MSGTYPE_AUTHCHARACTER");
const String MSGTYPE_AUTHCHARACTERAPPROVED("MSGTYPE_AUTHCHARACTERAPPROVED");
const String MSGTYPE_CHAR_CREATE_CP("MSGTYPE_CHAR_CREATE_CP");
const String MSGTYPE_COMBATEVENT("MSGTYPE_COMBATEVENT");
const String MSGTYPE_LOOT("MSGTYPE_LOOT");
const String MSGTYPE_LOOTITEM("MSGTYPE_LOOTITEM");
const String MSGTYPE_LOOTREMOVE("MSGTYPE_LOOTREMOVE");
const String MSGTYPE_GUISKILL("MSGTYPE_GUISKILL");
const String MSGTYPE_OVERRIDEACTION("MSGTYPE_OVERRIDEACTION");
const String MSGTYPE_QUESTLIST("MSGTYPE_QUESTLIST");
const String MSGTYPE_QUESTINFO("MSGTYPE_QUESTINFO");
const String MSGTYPE_GMGUI("MSGTYPE_GMGUI");
const String MSGTYPE_WORKCMD("MSGTYPE_WORKCMD");
const String MSGTYPE_BUDDY_LIST("MSGTYPE_BUDDY_LIST");
const String MSGTYPE_BUDDY_STATUS("MSGTYPE_BUDDY_STATUS");
const String MSGTYPE_MOTD("MSGTYPE_MOTD");
const String MSGTYPE_MOTDREQUEST("MSGTYPE_MOTDREQUEST");
const String MSGTYPE_QUESTION("MSGTYPE_QUESTION");
const String MSGTYPE_QUESTIONRESPONSE("MSGTYPE_QUESTIONRESPONSE");
const String MSGTYPE_SLOT_MOVEMENT("MSGTYPE_SLOT_MOVEMENT");
const String MSGTYPE_QUESTIONCANCEL("MSGTYPE_QUESTIONCANCEL");
const String MSGTYPE_GUILDMOTDSET("MSGTYPE_GUILDMOTDSET");
const String MSGTYPE_PLAYSOUND("MSGTYPE_PLAYSOUND");
const String MSGTYPE_CHARACTERDETAILS("MSGTYPE_CHARACTERDETAILS");
const String MSGTYPE_CHARDETAILSREQUEST("MSGTYPE_CHARDETAILSREQUEST");
const String MSGTYPE_CHARDESCUPDATE("MSGTYPE_CHARDESCUPDATE");
const String MSGTYPE_FACTION_INFO("MSGTYPE_FACTION_INFO");
const String MSGTYPE_QUESTREWARD("MSGTYPE_QUESTREWARD");
const String MSGTYPE_NAMECHANGE("MSGTYPE_NAMECHANGE");
const String MSGTYPE_GUILDCHANGE("MSGTYPE_GUILDCHANGE");
const String MSGTYPE_LOCKPICK("MSGTYPE_LOCKPICK");
const String MSGTYPE_GMSPAWNITEMS("MSGTYPE_GMSPAWNITEMS");
const String MSGTYPE_GMSPAWNTYPES("MSGTYPE_GMSPAWNTYPES");
const String MSGTYPE_GMSPAWNITEM("MSGTYPE_GMSPAWNITEM");
const String MSGTYPE_ADVICE("MSGTYPE_ADVICE");
const String MSGTYPE_ACTIVEMAGIC("MSGTYPE_ACTIVEMAGIC");
const String MSGTYPE_GROUPCHANGE("MSGTYPE_GROUPCHANGE");
const String MSGTYPE_MAPACTION("MSGTYPE_MAPACTION");
const String MSGTYPE_CLIENTSTATUS("MSGTYPE_CLIENTSTATUS");
const String MSGTYPE_TUTORIAL("MSGTYPE_TUTORIAL");
const String MSGTYPE_BANKING("MSGTYPE_BANKING");
const String MSGTYPE_REQUESTMOVEMENTS("MSGTYPE_REQUESTMOVEMENTS");
const String MSGTYPE_MOVEINFO("MSGTYPE_MOVEINFO");
const String MSGTYPE_MOVEMOD("MSGTYPE_MOVEMOD");
const String MSGTYPE_MOVELOCK("MSGTYPE_MOVELOCK");
const String MSGTYPE_CHAR_DELETE("MSGTYPE_CHAR_DELETE");
const String MSGTYPE_CHAR_CREATE_PARENTS("MSGTYPE_CHAR_CREATE_PARENTS");
const String MSGTYPE_CHAR_CREATE_CHILDHOOD("MSGTYPE_CHAR_CREATE_CHILDHOOD");
const String MSGTYPE_CHAR_CREATE_LIFEEVENTS("MSGTYPE_CHAR_CREATE_LIFEEVENTS");
const String MSGTYPE_CHAR_CREATE_UPLOAD("MSGTYPE_CHAR_CREATE_UPLOAD");
const String MSGTYPE_CHAR_CREATE_VERIFY("MSGTYPE_CHAR_CREATE_VERIFY");
const String MSGTYPE_CHAR_CREATE_NAME("MSGTYPE_CHAR_CREATE_NAME");
const String MSGTYPE_PERSIST_WORLD_REQUEST("MSGTYPE_PERSIST_WORLD_REQUEST");
const String MSGTYPE_PERSIST_WORLD("MSGTYPE_PERSIST_WORLD");
const String MSGTYPE_PERSIST_ACTOR_REQUEST("MSGTYPE_PERSIST_ACTOR_REQUEST");
const String MSGTYPE_PERSIST_ACTOR("MSGTYPE_PERSIST_ACTOR");
const String MSGTYPE_PERSIST_ITEM("MSGTYPE_PERSIST_ITEM");
const String MSGTYPE_PERSIST_ACTIONLOCATION("MSGTYPE_PERSIST_ACTIONLOCATION");
const String MSGTYPE_PERSIST_ALL("MSGTYPE_PERSIST_ALL");
const String MSGTYPE_REMOVE_OBJECT("MSGTYPE_REMOVE_OBJECT");
const String MSGTYPE_CHANGE_TRAIT("MSGTYPE_CHANGE_TRAIT");
const String MSGTYPE_DAMAGE_EVENT("MSGTYPE_DAMAGE_EVENT");
const String MSGTYPE_DEATH_EVENT("MSGTYPE_DEATH_EVENT");
const String MSGTYPE_TARGET_EVENT("MSGTYPE_TARGET_EVENT");
const String MSGTYPE_ZPOINT_EVENT("MSGTYPE_ZPOINT_EVENT");
const String MSGTYPE_BUY_EVENT("MSGTYPE_BUY_EVENT");
const String MSGTYPE_SELL_EVENT("MSGTYPE_SELL_EVENT");
const String MSGTYPE_PICKUP_EVENT("MSGTYPE_PICKUP_EVENT");
const String MSGTYPE_DROP_EVENT("MSGTYPE_DROP_EVENT");
const String MSGTYPE_LOOT_EVENT("MSGTYPE_LOOT_EVENT");
const String MSGTYPE_CONNECT_EVENT("MSGTYPE_CONNECT_EVENT");
const String MSGTYPE_MOVEMENT_EVENT("MSGTYPE_MOVEMENT_EVENT");
const String MSGTYPE_GENERIC_EVENT("MSGTYPE_GENERIC_EVENT");
const String MSGTYPE_SOUND_EVENT("MSGTYPE_SOUND_EVENT");
const String MSGTYPE_CHAR_CREATE_TRAITS("MSGTYPE_CHAR_CREATE_TRAITS");
const String MSGTYPE_STATS("MSGTYPE_STATS");
const String MSGTYPE_NPC_SETOWNER("MSGTYPE_NPC_SETOWNER");
const String MSGTYPE_PET_COMMAND("MSGTYPE_PET_COMMAND");
const String MSGTYPE_PET_SKILL("MSGTYPE_PET_SKILL");
const String MSGTYPE_CRAFT_INFO("MSGTYPE_CRAFT_INFO");
const String MSGTYPE_PETITION_REQUEST("MSGTYPE_PETITION_REQUEST");
const String MSGTYPE_HEART_BEAT("MSGTYPE_HEART_BEAT");
const String MSGTYPE_NPC_COMMAND("MSGTYPE_NPC_COMMAND");
const String MSGTYPE_MINIGAME_STARTSTOP("MSGTYPE_MINIGAME_STARTSTOP");
const String MSGTYPE_MINIGAME_BOARD("MSGTYPE_MINIGAME_BOARD");
const String MSGTYPE_MINIGAME_UPDATE("MSGTYPE_MINIGAME_UPDATE");
const String MSGTYPE_ENTRANCE("MSGTYPE_ENTRANCE");
const String MSGTYPE_GMEVENT_LIST("MSGTYPE_GMEVENT_LIST");
const String MSGTYPE_GMEVENT_INFO("MSGTYPE_GMEVENT_INFO");
const String MSGTYPE_SEQUENCE("MSGTYPE_SEQUENCE");
const String MSGTYPE_NPCRACELIST("MSGTYPE_NPCRACELIST");
const String MSGTYPE_INTRODUCTION("MSGTYPE_INTRODUCTION");

// Chat Message Types
const String CHAT_SYSTEM("CHAT_SYSTEM");
const String CHAT_SAY("CHAT_SAY");
const String CHAT_TELL("CHAT_TELL");
const String CHAT_GROUP("CHAT_GROUP");
const String CHAT_GUILD("CHAT_GUILD");
const String CHAT_AUCTION("CHAT_AUCTION");
const String CHAT_SHOUT("CHAT_SHOUT");
const String CHAT_ME("CHAT_ME");
const String CHAT_TELLSELF("CHAT_TELLSELF");
const String CHAT_REPORT("CHAT_REPORT");
const String CHAT_ADVISOR("CHAT_ADVISOR");
const String CHAT_ADVICE("CHAT_ADVICE");
const String CHAT_ADVICE_LIST("CHAT_ADVICE_LIST");
const String CHAT_SERVER_TELL("CHAT_SERVER_TELL");
const String CHAT_GM("CHAT_GM");
const String CHAT_SERVER_INFO("CHAT_SERVER_INFO");
const String CHAT_MY("CHAT_MY");
const String CHAT_NPC("CHAT_NPC");
const String CHAT_SYSTEM_BASE("CHAT_SYSTEM_BASE");
const String CHAT_PET_ACTION("CHAT_PET_ACTION");
const String CHAT_NPC_ME("CHAT_NPC_ME");
const String CHAT_NPC_MY("CHAT_NPC_MY");
const String CHAT_NPC_NARRATE("CHAT_NPC_NARRATE");

// Combat Event Types
const String COMBAT_DODGE("COMBAT_DODGE");
const String COMBAT_BLOCK("COMBAT_BLOCK");
const String COMBAT_DAMAGE("COMBAT_DAMAGE");
const String COMBAT_MISS("COMBAT_MISS");
const String COMBAT_OUTOFRANGE("COMBAT_OUTOFRANGE");
const String COMBAT_DEATH("COMBAT_DEATH");
const String COMBAT_DAMAGE_NEARLY_DEAD("COMBAT_DAMAGE_NEARLY_DEAD");

// Persist Item Flags
const String PERSIST_ITEM_NONE("NONE");
const String PERSIST_ITEM_NOPICKUP("NOPICKUP");
const String PERSIST_ITEM_COLLIDE("COLLIDE");

// Persist Actor flags
const String PERSIST_ACTOR_NONE("NONE");
const String PERSIST_ACTOR_NPC("NPC");
const String PERSIST_ACTOR_NAME_KNOWN("NAME_KNOWN");

// Dead Reckoning Data Flags
const String DR_DATA_NOT_MOVING("NOT_MOVING");
const String DR_DATA_ACTOR_MODE("ACTOR_MODE");
const String DR_DATA_ANG_VELOCITY("ANG_VELOCITY");
const String DR_DATA_X_VELOCITY("X_VELOCITY");
const String DR_DATA_Y_VELOCITY("Y_VELOCITY");
const String DR_DATA_Z_VELOCITY("Z_VELOCITY");
const String DR_DATA_X_WORLDVELOCITY("X_WORLDVELOCITY");
const String DR_DATA_Y_WORLDVELOCITY("Y_WORLDVELOCITY");
const String DR_DATA_Z_WORLDVELOCITY("Z_WORLDVELOCITY");
const String DR_DATA_ALL_DATA("ALL_DATA");

// Equipment Message Commands
const String EQUIP("EQUIP");
const String DEEQUIP("DEEQUIP");

// Player Modes
const String PLAYER_MODE_PEACE("PEACE");
const String PLAYER_MODE_COMBAT("COMBAT");
const String PLAYER_MODE_SPELL_CASTING("SPELL_CASTING");
const String PLAYER_MODE_WORK("WORK");
const String PLAYER_MODE_DEAD("DEAD");
const String PLAYER_MODE_SIT("SIT");
const String PLAYER_MODE_OVERWEIGHT("OVERWEIGHT");
const String PLAYER_MODE_EXHAUSTED("EXHAUSTED");
const String PLAYER_MODE_DEFEATED("DEFEATED");

// Quest Reward Message Type
const String QUEST_REWARD_OFFER_REWARDS("OFFER_REWARDS");
const String QUEST_REWARD_SELECT_REWARDS("SELECT_REWARDS");

// View Item Message Type
const String VIEW_ITEM_REQUEST("REQUEST");
const String VIEW_ITEM_DESCRIPTION("DESCRIPTION");

// System Message Types
const String SYSTEM_MSG_ERROR("MSG_ERROR");
const String SYSTEM_MSG_INFO("MSG_INFO");
const String SYSTEM_MSG_INFO_SERVER("MSG_INFO_SERVER");
const String SYSTEM_MSG_RESULT("MSG_RESULT");
const String SYSTEM_MSG_OK("MSG_OK");
const String SYSTEM_MSG_WHO("MSG_WHO");
const String SYSTEM_MSG_ACK("MSG_ACK");
const String SYSTEM_MSG_INFO_BASE("MSG_INFO_BASE");
const String SYSTEM_MSG_COMBAT("MSG_COMBAT");
const String SYSTEM_MSG_COMBAT_DODGE("MSG_COMBAT_DODGE");
const String SYSTEM_MSG_COMBAT_BLOCK("MSG_COMBAT_BLOCK");
const String SYSTEM_MSG_COMBAT_HITYOU("MSG_COMBAT_HITYOU");
const String SYSTEM_MSG_COMBAT_HITOTHER("MSG_COMBAT_HITOTHER");
const String SYSTEM_MSG_COMBAT_YOURHIT("MSG_COMBAT_YOURHIT");
const String SYSTEM_MSG_COMBAT_OTHERHIT("MSG_COMBAT_OTHERHIT");
const String SYSTEM_MSG_COMBAT_MISS("MSG_COMBAT_MISS");
const String SYSTEM_MSG_COMBAT_OWN_DEATH("MSG_COMBAT_OWN_DEATH");
const String SYSTEM_MSG_COMBAT_DEATH("MSG_COMBAT_DEATH");
const String SYSTEM_MSG_COMBAT_VICTORY("MSG_COMBAT_VICTORY");
const String SYSTEM_MSG_COMBAT_STANCE("MSG_COMBAT_STANCE");
const String SYSTEM_MSG_COMBAT_NEARLY_DEAD("MSG_COMBAT_NEARLY_DEAD");
const String SYSTEM_MSG_LOOT("MSG_LOOT");
const String SYSTEM_MSG_SEC("MSG_SEC");
const String SYSTEM_SEC_LEVEL0("SEC_LEVEL0");
const String SYSTEM_SEC_LEVEL1("SEC_LEVEL1");
const String SYSTEM_SEC_LEVEL2("SEC_LEVEL2");
const String SYSTEM_SEC_LEVEL3("SEC_LEVEL3");
const String SYSTEM_SEC_LEVEL4("SEC_LEVEL4");
const String SYSTEM_MSG_PURCHASE("MSG_PURCHASE");

// GUI Inventory Message Types
const String GUI_INVENTORY_LIST("LIST");
const String GUI_INVENTORY_REQUEST("REQUEST");
const String GUI_INVENTORY_UPDATE_REQUEST("UPDATE_REQUEST");
const String GUI_INVENTORY_UPDATE_LIST("UPDATE_LIST");

// Player Weather Mode
const String WEATHER_MODE_DAYNIGHT("DAYNIGHT");
const String WEATHER_MODE_WEATHER("WEATHER");

// Weather Types
const String WEATHER_TYPE_RAIN("RAIN");
const String WEATHER_TYPE_SNOW("SNOW");
const String WEATHER_TYPE_FOG("FOG");
const String WEATHER_TYPE_LIGHTNING("LIGHTNING");

// Active Magic Command Type
const String ACTIVE_MAGIC_ADD_CATEGORY("ADD_CATEGORY");
const String ACTIVE_MAGIC_REMOVE_CATEGORY("REMOVE_CATEGORY");

// GUI Interaction TYpes
const String GUI_INTERACTION_PICKUP("PICKUP");
const String GUI_INTERACTION_EXAMINE("EXAMINE");
const String GUI_INTERACTION_UNLOCK("UNLOCK");
const String GUI_INTERACTION_LOOT("LOOT");
const String GUI_INTERACTION_BUYSELL("BUYSELL");
const String GUI_INTERACTION_GIVE("GIVE");
const String GUI_INTERACTION_CLOSE("CLOSE");
const String GUI_INTERACTION_USE("USE");
const String GUI_INTERACTION_PLAYERDESC("PLAYERDESC");
const String GUI_INTERACTION_ATTACK("ATTACK");
const String GUI_INTERACTION_COMBINE("COMBINE");
const String GUI_INTERACTION_EXCHANGE("EXCHANGE");
const String GUI_INTERACTION_TRAIN("TRAIN");
const String GUI_INTERACTION_NPCTALK("NPCTALK");
const String GUI_INTERACTION_VIEWSTATS("VIEWSTATS");
const String GUI_INTERACTION_DISMISS("DISMISS");
const String GUI_INTERACTION_MARRIAGE("MARRIAGE");
const String GUI_INTERACTION_DIVORCE("DIVORCE");
const String GUI_INTERACTION_PLAYGAME("PLAYGAME");
const String GUI_INTERACTION_ENTER("ENTER");
const String GUI_INTERACTION_LOCK("LOCK");
const String GUI_INTERACTION_ENTERLOCKED("ENTERLOCKED");
const String GUI_INTERACTION_BANK("BANK");
const String GUI_INTERACTION_INTRODUCE("INTRODUCE");

// GUI Merchant Message Types
const String GUI_MERCHANT_MESSAGE_REQUEST("REQUEST");
const String GUI_MERCHANT_MESSAGE_MERCHANT("MERCHANT");
const String GUI_MERCHANT_MESSAGE_CATEGORIES("CATEGORIES");
const String GUI_MERCHANT_MESSAGE_CATEGORY("CATEGORY");
const String GUI_MERCHANT_MESSAGE_MONEY("MONEY");
const String GUI_MERCHANT_MESSAGE_ITEMS("ITEMS");
const String GUI_MERCHANT_MESSAGE_BUY("BUY");
const String GUI_MERCHANT_MESSAGE_SELL("SELL");
const String GUI_MERCHANT_MESSAGE_VIEW("VIEW");
const String GUI_MERCHANT_MESSAGE_CANCEL("CANCEL");

// GUI Skill Message Types
const String GUI_SKILL_MESSAGE_REQUEST("REQUEST");
const String GUI_SKILL_MESSAGE_BUY_SKILL("BUY_SKILL");
const String GUI_SKILL_MESSAGE_SKILL_LIST("SKILL_LIST");
const String GUI_SKILL_MESSAGE_SKILL_SELECTED("SKILL_SELECTED");
const String GUI_SKILL_MESSAGE_DESCRIPTION("DESCRIPTION");
const String GUI_SKILL_MESSAGE_QUIT("QUIT");

// Message types and elements
const String ELEMENT_ALL_MESSAGE_TYPE("psai:messagetype");

const String TYPE_CHAT_MESSAGE("psai:chatmessage");
const String ELEMENT_CHAT_TEXT("psai:text");
const String ELEMENT_CHAT_SPEAKER("psai:speaker");
const String ELEMENT_CHAT_SPEAKER_FROM("psai:from");
const String ELEMENT_CHAT_SPEAKER_TO("psai:to");
const String ELEMENT_CHAT_CHAT_TYPE("psai:chattype");

const String TYPE_COMBAT_MESSAGE("psai:combateventmessage");
const String ELEMENT_COMBAT_ATTACKER_ID("psai:attackerid");
const String ELEMENT_COMBAT_TARGET_ID("psai:targetid");
const String ELEMENT_COMBAT_DAMAGE("psai:damage");
const String ELEMENT_COMBAT_TARGET_LOCATION("psai:targetlocation");
const String ELEMENT_COMBAT_EVENT_TYPE("psai:combateventtype");

const String TYPE_DR_MESSAGE("psai:drmessage");
const String ELEMENT_DR_COUNTER("psai:counter");
const String ELEMENT_DR_ON_GROUND("psai:onground");
const String ELEMENT_DR_POSITION("psai:position");
const String ELEMENT_DR_VELOCITY("psai:velocity");
const String ELEMENT_DR_WORLD_VELOCITY("psai:worldvelocity");
const String ELEMENT_DR_Y_ROTATION("psai:yrotation");
const String ELEMENT_DR_SECTOR_NAME("psai:sectorname");
const String ELEMENT_DR_ANGULAR_VELOCITY("psai:angularvelocity");
const String ELEMENT_DR_ENTITY_ID("psai:entityid");

const String TYPE_EFFECT_MESSAGE("psai:effectmessage");
const String ELEMENT_EFFECT_MESSAGE_NAME("psai:name");
const String ELEMENT_EFFECT_MESSAGE_ANCHOR_ID("psai:anshorid");
const String ELEMENT_EFFECT_MESSAGE_TARGET_ID("psai:targetid");
const String ELEMENT_EFFECT_MESSAGE_CAST_DURATION("psai:castduration");
const String ELEMENT_EFFECT_MESSAGE_UID("psai:uid");
const String ELEMENT_EFFECT_MESSAGE_EFFECT_TEXT("psai:effecttext");

const String TYPE_GUI_ACTIVE_MAGIC_MESSAGE("psai:guiactivemagicmessage");
const String ELEMENT_GUI_ACTIVE_MAGIC_CATEGORY_LIST("psai:catrgorylist");
const String ELEMENT_GUI_ACTIVE_MAGIC_COMMAND("psai:command");

const String TYPE_GUI_INTERACT_MESSAGE("psai:guiinteractmessage");
const String ELEMENT_GUI_INTERACT_TYPE("psai:type");

const String TYPE_GUI_INVENTORY_MESSAGE("psai:guiinventorymessage");
const String ELEMENT_GUI_INVENTORY_ITEMS("psai:items");
const String ELEMENT_GUI_INVENTORY_TOTAL_ITEMS("psai:totalitens");
const String ELEMENT_GUI_INVENTORY_TOTAL_EMPTIED_SLOTS("psai:totalemptiedslots");
const String ELEMENT_GUI_INVENTORY_MAX_WEIGHT("psai:maxweight");
const String ELEMENT_GUI_INVENTORY_MONEY("psai:money");

const String TYPE_GUI_MERCHANT_MESSAGE("psai:guimerchantmessage");
const String ELEMENT_GUI_MERCHANT_COMMAND_TYPE("psai:commandtype");
const String ELEMENT_GUI_MERCHANT_MESSAGE_CONTENT("psai:messagecontent");

const String TYPE_GUI_SKILL_MESSAGE("psai:guiskillmessage");
const String ELEMENT_GUI_SKILL_COMMAND("psai:command");
const String ELEMENT_GUI_SKILL_COMMAND_DATA("psai:commanddata");
const String ELEMENT_GUI_SKILL_STRENGTH("psai:strength");
const String ELEMENT_GUI_SKILL_ENDURANCE("psai:endurance");
const String ELEMENT_GUI_SKILL_AGILITY("psai:agility");
const String ELEMENT_GUI_SKILL_WILL("psai:will");
const String ELEMENT_GUI_SKILL_CHARISMA("psai:charisma");
const String ELEMENT_GUI_SKILL_HIT_POINTS("psai:hitpoints");
const String ELEMENT_GUI_SKILL_MANA("psai:mana");
const String ELEMENT_GUI_SKILL_PHYSICAL_STAMINA("psai:physicalstamina");
const String ELEMENT_GUI_SKILL_MENTAL_STAMINA("psai:mentalstamina");
const String ELEMENT_GUI_SKILL_MAX_HIT_POINTS("psai:maxhitpoints");
const String ELEMENT_GUI_SKILL_MAX_MANA("psai:max_mana");
const String ELEMENT_GUI_SKILL_MAX_PHYSICAL_STAMINA("psai:maxphysicalstamina");
const String ELEMENT_GUI_SKILL_MAX_MENTAL_STAMINA("psai:maxmentalstamina");

const String TYPE_GUI_TARGET_UPDATE_MESSAGE("psai:guitargetupdatemessage");
const String ELEMENT_GUI_TARGET_UPDATE_CLIENT_ID("psai:clientid");
const String ELEMENT_GUI_TARGET_UPDATE_TARGET_ID("psai:targetid");

const String TYPE_MODE_MESSAGE("psai:modemessage");
const String ELEMENT_MODE_ACTOR_ID("psai:actorid");
const String ELEMENT_MODE_MODE("psai:mode");
const String ELEMENT_MODE_STANCE("psai:stance");

const String TYPE_MOVE_LOCK_MESSAGE("psai:movelockmessage");
const String ELEMENT_MOVE_LOCK_LOCKED("psai:locked");

const String TYPE_NEW_SECTOR_MESSAGE("psai:newsectormessage");
const String ELEMENT_NEW_SECTOR_OLD_SECTOR("psai:oldsector");
const String ELEMENT_NEW_SECTOR_NEW_SECTOR("psai:newsector");
const String ELEMENT_NEW_SECTOR_POSITION("psai:position");

const String TYPE_PERSIST_ACTION_LOCATION_MESSAGE("psai:persistactionlocationmessage");
const String ELEMENT_PERSIST_ACTION_LOCATION_SECTOR("psai:sector");
const String ELEMENT_PERSIST_ACTION_LOCATION_MESH("psai:mesh");
const String ELEMENT_PERSIST_ACTION_LOCATION_ID("psai:id");
const String ELEMENT_PERSIST_ACTION_LOCATION_TYPE("psai:type");

const String TYPE_PERSIST_ACTOR_MESSAGE("psai:persistactormessage");
const String ELEMENT_PERSIST_ACTOR_DR_MESSAGE("psai:drmessage");
const String ELEMENT_PERSIST_ACTOR_NAME("psai:name");
const String ELEMENT_PERSIST_ACTOR_GUILD("psai:guild");
const String ELEMENT_PERSIST_ACTOR_FACT_NAME("psai:factname");
const String ELEMENT_PERSIST_ACTOR__FILE_NAME("psai:filename");
const String ELEMENT_PERSIST_ACTOR_RACE("psai:race");
const String ELEMENT_PERSIST_ACTOR_GENDER("psai:gender");
const String ELEMENT_PERSIST_ACTOR_HELM_GROUPS("psai:helmgroups");
const String ELEMENT_PERSIST_ACTOR_TOP("psai:top");
const String ELEMENT_PERSIST_ACTOR_BOTTOM("psai:bottom");
const String ELEMENT_PERSIST_ACTOR_OFFSET("psai:offset");
const String ELEMENT_PERSIST_ACTOR_TYPE("psai:type");
const String ELEMENT_PERSIST_ACTOR_MASQUERADED_TYPE("psai:masqueradedtype");
const String ELEMENT_PERSIST_ACTOR_SERVER_MODE("psai:servermode");
const String ELEMENT_PERSIST_ACTOR_PLAYER_ID("psai:playerid");
const String ELEMENT_PERSIST_ACTOR_GROUP_ID("psai:groupid");
const String ELEMENT_PERSIST_ACTOR_OWNER_EID("psai:ownereid");
const String ELEMENT_PERSIST_ACTOR_CONTROL("psai:control");
const String ELEMENT_PERSIST_ACTOR_FLAGS("psai:flags");
const String ELEMENT_PERSIST_ACTOR_INSTANCE("psai:instance");

const String TYPE_PERSIST_ITEM_MESSAGE("psai:persistitemmessage");
const String ELEMENT_PERSIST_ITEM_NAME("psai:name");
const String ELEMENT_PERSIST_ITEM_FACT_NAME("psai:factname");
const String ELEMENT_PERSIST_ITEM_FILE_NAME("psai:filename");
const String ELEMENT_PERSIST_ITEM_SECTOR("psai:sector");
const String ELEMENT_PERSIST_ITEM_POSITION("psai:position");
const String ELEMENT_PERSIST_ITEM_Y_ROTATION("psai:yrotation");
const String ELEMENT_PERSIST_ITEM_ID("psai:id");
const String ELEMENT_PERSIST_ITEM_TYPE("psai:type");
const String ELEMENT_PERSIST_ITEM_FLAGS("psai:flags");

const String TYPE_PLAY_SOUND_MESSAGE("psai:playsoundmessage");
const String ELEMENT_PLAY_SOUND_SOUND("psai:sound");

const String TYPE_QUEST_LIST_MESSAGE("psai:questlistmessage");
const String ELEMENT_QUEST_LIST_QUEST_XML("psai:questxml");

const String TYPE_QUEST_REWARD_MESSAGE("psai:questrewardmessage");
const String ELEMENT_QUEST_REWARD_TYPE("psai:type");
const String ELEMENT_QUEST_REWARD_NEW_VALUE("psai:newvalue");

const String TYPE_REMOVE_OBJECT_MESSAGE("psai:removeobjectmessage");
const String ELEMENT_REMOVE_OBJECT_OBJECT_ID("psai:objectid");

const String TYPE_SOUND_EVENT_MESSAGE("psai:soundeventmessage");
const String ELEMENT_SOUNT_EVENT_TYPE("psai:soundeventtype");

const String TYPE_SPELL_CANCEL_MESSAGE("psai:spellcancelmessage");
// empty message

const String TYPE_SPELL_CAST_MESSAGE("psai:spellcastmessage");
const String ELEMENT_SPELL_CAST_SPELL("psai:spell");
const String ELEMENT_SPELL_CAST_K_FACTOR("psai:kfactor");

const String TYPE_STAT_DR_MESSAGE("psai:statdrmessage");
const String ELEMENT_STAT_DR_USEFUL("psai:useful");
const String ELEMENT_STAT_DR_ENTITY_ID("psai:entityid");
const String ELEMENT_STAT_DR_STATS_DIRTY("psai:statsdirty");
const String ELEMENT_STAT_DR_COUNTER("psai:counter");

const String TYPE_STATS_MESSAGE("psai:statsmessage");
const String ELEMENT_STATS_HIT_POINTS("psai:hp");
const String ELEMENT_STATS_MANA("psai:mana");
const String ELEMENT_STATS_WEIGHT("psai:weight");
const String ELEMENT_STATS_CAPACITY("psai:capacity");

const String TYPE_STOP_EFFECT_MESSAGE("psai:stopeffectmessage");
const String ELEMENT_STOP_EFFECT_UID("psai:uid");

const String TYPE_SYSTEM_MESSAGE("psai:systemmessage");
const String ELEMENT_TEXT("psai:text");
const String ELEMENT_SYSTEM_TYPE("psai:type");

const String TYPE_UPDATE_OBJECT_NAME_MESSAGE("psai:updateobjectname");
const String ELEMENT_UPDATE_OBJECT_NAME_OBJECT_ID("psai:objectid");
const String ELEMENT_UPDATE_OBJECT_NAME_NEW_NAME("psai:newname");

const String TYPE_VIEW_ITEM_DESCRIPTION_MESSAGE("psai:viewitemdescriptionmessage");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_ITEM_NAME("psai:itemname");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_ITEM_DESCRIPTION("psai:itemdescription");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_STACK_COUNT("psai:stackcount");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_CONTAINER_ID("psai:containerid");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_SLOT_ID("psai:slotid");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_HAS_CONTENTS("psai:hascontents");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_TO_CLIENT("psai:toclient");
const String ELEMENT_VIEW_ITEM_DESCRIPTION_CONTENTS("psai:contents");

const String TYPE_VIEW_ITEM_UPDATE_MESSAGE("psai:viewitemupdatemessage");
const String ELEMENT_VIEW_ITEM_UPDATE_CLEAR_SLOT("psai:clearslot");
const String ELEMENT_VIEW_ITEM_UPDATE_TO_CLIENT("psai:toclient");
const String ELEMENT_VIEW_ITEM_UPDATE_CONTAINER_ID("psai:containerid");
const String ELEMENT_VIEW_ITEM_UPDATE_NAME("psai:name");
const String ELEMENT_VIEW_ITEM_UPDATE_ICON("psai:icon");
const String ELEMENT_VIEW_ITEM_UPDATE_SLOT_ID("psai:slotid");
const String ELEMENT_VIEW_ITEM_UPDATE_STACK_COUNT("psai:stackcount");
const String ELEMENT_VIEW_ITEM_UPDATE_OWNER_ID("psai:ownerid");

const String TYPE_WEATHER_MESSAGE("psai:weathermessage");
const String ELEMENT_WEATHER_MINUTE("psai:minute");
const String ELEMENT_WEATHER_HOUR("psai:hour");
const String ELEMENT_WEATHER_DAY("psai:day");
const String ELEMENT_WEATHER_MONTH("psai:month");
const String ELEMENT_WEATHER_YEAR("psai:year");
const String ELEMENT_WEATHER_WEATHER("psai:weather");

const String XML_HEADER("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
const String PSAI_MESSAGE_ELEMENT_START("psai:psaimessage");
const String PSAI_MESSAGE_ELEMENT_END("psai:psaimessage");

const String PSAI_SCHEMA_LOCATION("http://www.zarniwoops.plus.com/psai/xml http://www.zarniwoops.plus.com/psai/xml/psaiXmlMessages.xsd");
const String PSAI_NAMESPACE("http://www.zarniwoops.plus.com/psai/xml/psaiXmlMessages.xsd");

const String ELEMENT_VECTOR_X("x");
const String ELEMENT_VECTOR_Y("y");
const String ELEMENT_VECTOR_Z("z");

const String ELEMENT_CONTAINER_CONTENTS_NAME("name");
const String ELEMENT_CONTAINER_CONTENTS_ICON("icon");
const String ELEMENT_CONTAINER_CONTENTS_SLOT_ID("slotid");
const String ELEMENT_CONTAINER_CONTENTS_STACK_COUNT("stackcount");
const String ELEMENT_CONTAINER_CONTENTS_PURIFY_STATUS("purifystatus");

const String ELEMENT_CLIENT_NUM("psai:clientnum");
}
