// This file is automatically generated.
#include "cssysdef.h"

struct CS_IMPORT_SYM _Bind_psserver_static_plugins_CEL
{
  _Bind_psserver_static_plugins_CEL ();
};
namespace { _Bind_psserver_static_plugins_CEL bind_psserver_static_plugins_CEL; }

